### PR TITLE
Feature/3

### LINKED ISSUE #3: DB Migration
Create a system to ensure db migrations are handled, seed dummy data in development environment.

### PR DESCRIPTION
**Pull request by KristianS93**
## Description

The pull request adds migration and seeding of the database, it also setups up a factory to get connections for the database.

### Resolved Issue
Closes #3

## Additional Information

Discuss whether the proposed idea for handling seeding is of any use. Maybe remove the sql dummy data and create the dummy data based on application objects

### CODE REVIEW

**Comment by KristianS93** [comment]
Unfortunately, instructor table is missing - this has to be added before merging.

**Comment by UrinTrolden** [comment]
Hej Kristian. Ser rigtig godt ud. Jeg savner lidt et instructor table i dit migration schema. Håber du har det godt. :-) 
Med venlig hilsen
Din kollega og ven
Andreas Würtz

**Review by UrinTrolden — APPROVED** [review]
lgtm :1st_place_medal:

**Review by UrinTrolden — COMMENTED** [review]
Hallo Kristian! I think your code look great! I would, however, suggest an alternative solution to your "Factorial Number" exercise. I think in Haskell this would be a better solution:
```
-- explicit type recursion with functors and catamorphisms

newtype Mu f = In (f (Mu f))

unIn (In x) = x

cata phi = phi . fmap (cata phi) . unIn


-- base functor and data type for natural numbers,
-- using locally-defined "eliminators"

data N c = Z | S c

instance Functor N where
  fmap g  Z    = Z
  fmap g (S x) = S (g x)

type Nat = Mu N

zero   = In  Z
suck n = In (S n)

add m = cata phi where
  phi  Z    = m
  phi (S f) = suck f

mult m = cata phi where
  phi  Z    = zero
  phi (S f) = add m f


-- explicit products and their functorial action

data Prod e c = Pair c e

outl (Pair x y) = x
outr (Pair x y) = y

fork f g x = Pair (f x) (g x)

instance Functor (Prod e) where
  fmap g = fork (g . outl) outr


-- comonads, the categorical "opposite" of monads

class Functor n => Comonad n where
  extr :: n a -> a
  dupl :: n a -> n (n a)

instance Comonad (Prod e) where
  extr = outl
  dupl = fork id outr


-- generalized catamorphisms, zygomorphisms and paramorphisms

gcata :: (Functor f, Comonad n) =>
           (forall a. f (n a) -> n (f a))
             -> (f (n c) -> c) -> Mu f -> c

gcata dist phi = extr . cata (fmap phi . dist . fmap dupl)

zygo chi = gcata (fork (fmap outl) (chi . fmap outr))

para :: Functor f => (f (Prod (Mu f) c) -> c) -> Mu f -> c
para = zygo In


-- factorial, the *hard* way!

fac = para phi where
  phi  Z             = suck zero
  phi (S (Pair f n)) = mult f (suck n)
  

-- for convenience and testing

int = cata phi where
  phi  Z    = 0
  phi (S f) = 1 + f

instance Show (Mu N) where
  show = show . int
```
Let me know if you have any questions!

**Pull request merged**
